name: parser
channels:
  - conda-forge
  - defaults
dependencies:
  - jsmin=2.2.2
  - python-docx=0.8.6
  - blas=1.0
  - certifi=2018.8.24
  - click=6.7
  - flask=1.0.2
  - icc_rt=2017.0.4
  - intel-openmp=2018.0.3
  - itsdangerous=0.24
  - jinja2=2.10
  - libiconv=1.15
  - libxml2=2.9.8
  - libxslt=1.1.32
  - lxml=4.2.3
  - markupsafe=1.0
  - mkl=2018.0.3
  - mkl_fft=1.0.4
  - mkl_random=1.0.1
  - numpy=1.15.0
  - numpy-base=1.15.0
  - pandas=0.23.3
  - pip=10.0.1
  - python=3.6.6
  - python-dateutil=2.7.3
  - pytz=2018.5
  - setuptools=39.2.0
  - six=1.11.0
  - werkzeug=0.14.1
  - wheel=0.31.1
  - wincertstore=0.2
  - xlrd=1.1.0
  - zlib=1.2.11